# Generated by Django 2.1.7 on 2019-03-15 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('smashkids_app', '0005_auto_20190315_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 7, 43, 28, 763532, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 7, 43, 28, 762945, tzinfo=utc)),
        ),
    ]
